### ISSUE TITLE
Error: Command failed: unoconv -f pdf

### ISSUE THREAD

**Issue by Gowtham029** [vworld4u/office-converter#3]
Hi,
I am using Windows 7.
Node v8.X

I am getting the following error 
```
{ Error: Command failed: unoconv -f pdf "./files/Logs.docx"
'unoconv' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:276:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'unoconv -f pdf "./files/Logs.docx"' }
```
how to solve this?

Thanks.

**Comment by pkchoudhary1211** [comment]
Is there any solution ??

**Comment by pkchoudhary1211** [comment]
I got Solution You Need to install
unoconv
for more [info](https://www.npmjs.com/package/unoconv)

**Comment by wonjeongpark-THEHRDer** [comment]
Hi, there!
Could you let me know your solution?
I am trying install unoconv on windows but still not working.
I got a error msg same as yours.
thx
@Gowtham029 @pkchoudhary1211

**Comment by Gowtham029** [comment]
Hi @wonjeongpark-THEHRDer ,

I haven't found the solution yet, let you know if I find it.
